//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding4Fun.TransactSql.Analyzers {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coding4Fun.TransactSql.Analyzers.RuleResources", typeof(RuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create ResourceManager for {0} from {1}..
        /// </summary>
        internal static string CannotCreateResourceManager {
            get {
                return ResourceManager.GetString("CannotCreateResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP (N) requires ORDER BY clause.
        /// </summary>
        internal static string NotDeterministicSelect_Description {
            get {
                return ResourceManager.GetString("NotDeterministicSelect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP (N) requires ORDER BY clause.
        /// </summary>
        internal static string NotDeterministicSelect_RuleName {
            get {
                return ResourceManager.GetString("NotDeterministicSelect_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name &apos;{0}&apos; doesn&apos;t match the pattern: &apos;{1}&apos;.
        /// </summary>
        internal static string ObjectName_ProblemDescription {
            get {
                return ResourceManager.GetString("ObjectName_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of object name format.
        /// </summary>
        internal static string ObjectName_RuleName {
            get {
                return ResourceManager.GetString("ObjectName_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name has to include [schema_name] and [object_name], but was: {0}.
        /// </summary>
        internal static string SchemaRequire_ProblemDescription {
            get {
                return ResourceManager.GetString("SchemaRequire_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require schema name.
        /// </summary>
        internal static string SchemaRequire_RuleName {
            get {
                return ResourceManager.GetString("SchemaRequire_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has invalid value.
        /// </summary>
        internal static string StringLiteral_ProblemDescription {
            get {
                return ResourceManager.GetString("StringLiteral_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String literal validation.
        /// </summary>
        internal static string StringLiteral_RuleName {
            get {
                return ResourceManager.GetString("StringLiteral_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; doesn&apos;t contain a description.
        /// </summary>
        internal static string TableDescription_ColumnDoesNotContainDescription {
            get {
                return ResourceManager.GetString("TableDescription_ColumnDoesNotContainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for documentation existence.
        /// </summary>
        internal static string TableDescription_RuleName {
            get {
                return ResourceManager.GetString("TableDescription_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; doesn&apos;t contain a description.
        /// </summary>
        internal static string TableDescription_TableDoesNotContainDescription {
            get {
                return ResourceManager.GetString("TableDescription_TableDoesNotContainDescription", resourceCulture);
            }
        }
    }
}
